# WARN:
# This file is autogenerated and should not be modified directly. See scaffold project (url: https://github.com/TwinPlay-AI/scaffold)

.DEFAULT_GOAL := help

PROJECT_NAME := $$(cat .twinplay.json | jq -r .project_name)
PROJECT_FORCE_INIT := false
VIRTUAL_ENV := true

.PHONY: help
help: ## Helper
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'

.PHONY: deps
deps: ## Install deps
	@chmod +x ./scripts/deps.sh && ./scripts/deps.sh $(VIRTUAL_ENV)

.PHONY: init
init: ## Initialize the project
	@gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/TwinPlay-AI/scaffold/contents/init.sh | jq -r '.content' | base64 -d > init.sh | chmod +x init.sh
	@./init.sh $(PROJECT_NAME) $(PROJECT_FORCE_INIT)

.PHONY: setup
setup: deps ## Setup local environment

.PHONY: lint
lint: ## Lint code with pre-commit
	pre-commit run --all-files

.PHONY: project-name
project-name: ## Print project name
	@echo $(PROJECT_NAME)

include Makefile.project
