const sidebars = {
  menu: [
    {
      type: 'category',
      label: '📹 Utilizzo Camera',
      items: [
        {
          type: 'autogenerated',
          dirName: 'cam',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Utilizzo Camera',
        slug: '/',
        keywords: ['guides'],
      }
    },
    {
      type: 'category',
      label: '💻 WebApp',
      items: [
        {
          type: 'autogenerated',
          dirName: 'webapp',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'WebApp',
        keywords: ['guides'],
      }
    },
    {
      type: 'category',
      label: '📣 Social',
      items: [
        {
          type: 'autogenerated',
          dirName: 'social',
        },
      ],
      link: {
        type: 'generated-index',
        title: 'Social',
        keywords: ['guides'],
      }
    },
    'download'
  ]
};

export default sidebars;
