FROM mcr.microsoft.com/devcontainers/javascript-node:22-bullseye

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3000

USER node

CMD ["yarn", "start"]
